// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking_VIP.Data;

#nullable disable

namespace parkingvip.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230125030608_initiala")]
    partial class initiala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parking_VIP.Data.Entities.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("VehiculoId");

                    b.ToTable("tipo_Vehiculos");
                });

            modelBuilder.Entity("Parking_VIP.Data.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Estado")
                        .HasColumnType("real");

                    b.Property<DateTime>("H_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("H_salida")
                        .HasColumnType("datetime2");

                    b.Property<string>("N_parqueadero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("vehiculos");
                });

            modelBuilder.Entity("Parking_VIP.Data.Entities.TipoVehiculo", b =>
                {
                    b.HasOne("Parking_VIP.Data.Entities.Vehiculo", "Vehiculo")
                        .WithMany("TipoVehiculos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Parking_VIP.Data.Entities.Vehiculo", b =>
                {
                    b.Navigation("TipoVehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
